start: [includes] export_module import_module* namespace+

includes: "module;" include*

export_module: "export module" MODULE_NAME ";"

import_module: MODULE_IMPORT MODULE_NAME ";"

MODULE_IMPORT: "import" | "export import"

MODULE_NAME: (NAME | "." | ":")+

%import .dig (include, namespace, NAME)

%import common.WS
%import common.C_COMMENT
%import common.CPP_COMMENT

%ignore WS
%ignore C_COMMENT
%ignore CPP_COMMENT
