name: Build and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # pull_request_target:
  #   branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.compiler.os }}
    # permissions:
    #   pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]
        compiler:
          - name: gcc
            version: 14
            os: ubuntu-latest
          # Add back when gcc-15 can be used on ubuntu-latest or mac-os
          # - name: gcc
          #   version: 15
          #   os: macos-15
          # - name: gcc
          #   version: 15
          #   std_module: std-module
          #   os: macos-15
          - name: clang
            version: 20
            os: ubuntu-latest
          - name: clang
            version: 20
            std_module: std-module
            os: ubuntu-latest
          - name: cl
            header_only: header-only
            os: windows-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Set up Conan
      if: runner.os != 'macos'
      uses: turtlebrowser/get-conan@main

    - name: Set up Mold linker on linux
      if: runner.os == 'linux'
      uses: rui314/setup-mold@v1

    - name: Set up Conan and GCC on mac
      if: runner.os == 'macos' && matrix.compiler.name == 'gcc'
      run: |
        brew install conan
        wget https://github.com/macports/macports-base/releases/download/v2.10.7/MacPorts-2.10.7-15-Sequoia.pkg
        sudo installer -pkg ./MacPorts-2.10.7-15-Sequoia.pkg -target /
        export PATH=$PATH:/opt/local/bin
        sudo port install gcc-devel
        g++ --version

    - name: Set up GCC on linux
      if: runner.os == 'linux' && matrix.compiler.name == 'gcc'
      env:
          GCC_VER: ${{ matrix.compiler.version }}
      run: |
        sudo apt install -y gcc-${GCC_VER} g++-${GCC_VER}
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-${GCC_VER} 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-${GCC_VER} 100
        sudo update-alternatives --set cc /usr/bin/gcc-${GCC_VER}
        sudo update-alternatives --set c++ /usr/bin/g++-${GCC_VER}

    - name: Set up Clang
      if: matrix.compiler.name == 'clang'
      env:
        CLANG_VER: ${{ matrix.compiler.version }}
      run: |
        wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- ${CLANG_VER}
        sudo apt install clang-tools-${CLANG_VER} libc++-${CLANG_VER}-dev
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${CLANG_VER} 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${CLANG_VER} 100
        sudo update-alternatives --set cc /usr/bin/clang-${CLANG_VER}
        sudo update-alternatives --set c++ /usr/bin/clang++-${CLANG_VER}

    - name: "Conan: Install dependencies"
      working-directory: ${{ github.workspace }}
      env:
        BUILD_TYPE: ${{ matrix.build_type }}
      run: |
        conan profile detect
        conan install . --output-folder=build --build=missing --profile=conanprofile.txt --settings=build_type=${{ matrix.build_type }}

    - name: Configure CMake ${{ matrix.compiler.std_module }}
      working-directory: ${{ github.workspace }}/build
      run: >
        cmake ..
        --preset conan-default
        -DDI_BUILD_TESTS=TRUE
        -DDI_COMPRESS_TYPES=TRUE
        -DCMAKE_COLOR_DIAGNOSTICS=TRUE
        -DCMAKE_CXX_MODULE_STD=${{ matrix.compiler.std_module && 'TRUE' || 'FALSE' }}

    - name: Build
        ${{ matrix.compiler.header_only }}
        ${{ matrix.compiler.allow_build_failure }}
      id: build
      continue-on-error: ${{ !!matrix.compiler.allow_build_failure }}
      working-directory: ${{ github.workspace }}/build
      run: >
        cmake --build .
        --config ${{ matrix.build_type }}
        ${{ matrix.compiler.header_only && '-t di_tests_headers' || '' }}

    # - uses: mainmatter/continue-on-error-comment@v1
    #   if: matrix.compiler.allow_build_failure
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     outcome: ${{ steps.build.outcome }}
    #     test-id: Allowed failure compiling with ${{ matrix.compiler.name }}

    - name: Test
      if: steps.build.outcome == 'success'
      working-directory: ${{ github.workspace }}/build
      run: >
        ctest
        --verbose
        --build-config ${{ matrix.build_type }}
        ${{ matrix.compiler.header_only && '-R di_tests_headers' || '' }}
